server:
  port: 8080

spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://sentinel.his:8080
  rabbitmq:
    host: rabbitmq.his
    port: 5672
    username: admin
    password: admin
  redis:
    host: redis.default
#阿里云 短信
aliyun:
  sms:
    regionId: default
    accessKeyId: LTAI0YbQf3pX8WqC
    secret: jX8D04DmDI3gGKjW5kaFYSzugfqmmT
