server:
  port: 8207
spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://sentinel.his:8080
  rabbitmq:
    host: rabbitmq.his
    port: 5672
    username: admin
    password: admin